name: Update Whos In Space

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-whos-in-space:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Clean and install dependencies
      run: |
        rm -rf node_modules
        npm install

    - name: Run updateWhosInSpace
      run: node tools/updateWhosInSpace.js

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add whosinspace/people-in-space.json
        git commit -m "Update people-in-space.json via GitHub Actions" || echo "No changes to commit"
        git push
